# Generated by Django 5.1.4 on 2025-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPDFs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_flujo', models.BigIntegerField(help_text='ID del flujo de crédito procesado.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de generación del PDF.')),
                ('pdf_file', models.FileField(help_text='Archivo PDF del plan de pagos.', upload_to='planes_de_pago/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Historial de PDF',
                'verbose_name_plural': 'Historiales de PDFs',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
