# Generated by Django 5.1.4 on 2025-10-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpdfs',
            name='k_flujo',
        ),
        migrations.AddField(
            model_name='historialpdfs',
            name='cedula_cliente',
            field=models.CharField(blank=True, default='', help_text='Cédula del cliente asociado al crédito.', max_length=20),
        ),
        migrations.AddField(
            model_name='historialpdfs',
            name='obligacion',
            field=models.CharField(default='', help_text='Número de obligación único por crédito.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historialpdfs',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de generación del PDF y envío al correo.'),
        ),
    ]
